import { MinlanCategory, MinlanWord, MinlanCommunityStats } from "./types";

export const MOCK_MINLAN_CATEGORIES: MinlanCategory[] = [
  {
    id: "cat-1",
    slug: "gunluk-yasam",
    name_tr: "Günlük Yaşam & Ev",
    icon: "🏠",
    tier: 1,
    unlock_requirement_level: 1,
    display_order: 1,
    enabled: true,
  },
  {
    id: "cat-2",
    slug: "yiyecek-icecek",
    name_tr: "Yiyecek & İçecek",
    icon: "🍽️",
    tier: 1,
    unlock_requirement_level: 2,
    display_order: 2,
    enabled: true,
  },
  {
    id: "cat-3",
    slug: "seyahat-doga",
    name_tr: "Seyahat & Doğa",
    icon: "✈️",
    tier: 1,
    unlock_requirement_level: 3,
    display_order: 3,
    enabled: true,
  },
  {
    id: "cat-4",
    slug: "saglik-vucut",
    name_tr: "Sağlık & Vücut",
    icon: "🩺",
    tier: 1,
    unlock_requirement_level: 4,
    display_order: 4,
    enabled: true,
  },
  {
    id: "cat-5",
    slug: "meslekler-toplum",
    name_tr: "Meslekler & Toplum",
    icon: "💼",
    tier: 1,
    unlock_requirement_level: 5,
    display_order: 5,
    enabled: true,
  },
  {
    id: "cat-6",
    slug: "alisveris-finans",
    name_tr: "Alışveriş & Finans",
    icon: "🛒",
    tier: 1,
    unlock_requirement_level: 6,
    display_order: 6,
    enabled: true,
  },
  {
    id: "cat-7",
    slug: "duygular-kisilik",
    name_tr: "Duygular & Kişilik",
    icon: "😊",
    tier: 1,
    unlock_requirement_level: 7,
    display_order: 7,
    enabled: true,
  },
  {
    id: "cat-8",
    slug: "sanat-spor",
    name_tr: "Sanat & Spor",
    icon: "🎨",
    tier: 1,
    unlock_requirement_level: 8,
    display_order: 8,
    enabled: true,
  },
  {
    id: "cat-9",
    slug: "teknoloji-medya",
    name_tr: "Teknoloji & Medya",
    icon: "💻",
    tier: 1,
    unlock_requirement_level: 9,
    display_order: 9,
    enabled: true,
  },
];

export const MOCK_MINLAN_WORDS: MinlanWord[] = [
  // --- Category 1: Günlük Yaşam ---
  {
    id: "w-101",
    category_id: "cat-1",
    word_order: 1,
    lang_tr: "Merhaba",
    lang_en: "Hello",
    lang_de: "Hallo",
    lang_fr: "Bonjour",
    lang_es: "Hola",
    lang_it: "Ciao",
    lang_pt: "Olá",
    lang_ar: "مرحبا",
    lang_ko: "안녕하세요",
  },
  {
    id: "w-102",
    category_id: "cat-1",
    word_order: 2,
    lang_tr: "Teşekkür ederim",
    lang_en: "Thank you",
    lang_de: "Danke",
    lang_fr: "Merci",
    lang_es: "Gracias",
    lang_it: "Grazie",
    lang_pt: "Obrigado",
    lang_ar: "شكرا",
    lang_ko: "감사합니다",
  },
  {
    id: "w-103",
    category_id: "cat-1",
    word_order: 3,
    lang_tr: "Su",
    lang_en: "Water",
    lang_de: "Wasser",
    lang_fr: "Eau",
    lang_es: "Agua",
    lang_it: "Acqua",
    lang_pt: "Água",
    lang_ar: "ماء",
    lang_ko: "물",
  },
  {
    id: "w-104",
    category_id: "cat-1",
    word_order: 4,
    lang_tr: "Kitap",
    lang_en: "Book",
    lang_de: "Buch",
    lang_fr: "Livre",
    lang_es: "Libro",
    lang_it: "Libro",
    lang_pt: "Livro",
    lang_ar: "كتاب",
    lang_ko: "책",
  },
  {
    id: "w-105",
    category_id: "cat-1",
    word_order: 5,
    lang_tr: "Güneş",
    lang_en: "Sun",
    lang_de: "Sonne",
    lang_fr: "Soleil",
    lang_es: "Sol",
    lang_it: "Sole",
    lang_pt: "Sol",
    lang_ar: "شمس",
    lang_ko: "태양",
  },
  {
    id: "w-106",
    category_id: "cat-1",
    word_order: 6,
    lang_tr: "Arkadaş",
    lang_en: "Friend",
    lang_de: "Freund",
    lang_fr: "Ami",
    lang_es: "Amigo",
    lang_it: "Amico",
    lang_pt: "Amigo",
    lang_ar: "صديق",
    lang_ko: "친구",
  },
  {
    id: "w-107",
    category_id: "cat-1",
    word_order: 7,
    lang_tr: "Zaman",
    lang_en: "Time",
    lang_de: "Zeit",
    lang_fr: "Temps",
    lang_es: "Tiempo",
    lang_it: "Tempo",
    lang_pt: "Tempo",
    lang_ar: "وقت",
    lang_ko: "시간",
  },

  // --- Category 2: Teknoloji & Yapay Zekâ ---
  {
    id: "w-201",
    category_id: "cat-2",
    word_order: 1,
    lang_tr: "Yapay Zekâ",
    lang_en: "Artificial Intelligence",
    lang_de: "Künstliche Intelligenz",
    lang_fr: "Intelligence Artificielle",
    lang_es: "Inteligencia Artificial",
    lang_it: "Intelligenza Artificiale",
    lang_pt: "Inteligência Artificial",
    lang_ar: "الذكاء الاصطناعي",
    lang_ko: "인공지능",
  },
  {
    id: "w-202",
    category_id: "cat-2",
    word_order: 2,
    lang_tr: "Yazılım",
    lang_en: "Software",
    lang_de: "Software",
    lang_fr: "Logiciel",
    lang_es: "Software",
    lang_it: "Software",
    lang_pt: "Software",
    lang_ar: "برمجيات",
    lang_ko: "소프트웨어",
  },

  // --- Category 3: Bilim & Keşif ---
  {
    id: "w-301",
    category_id: "cat-3",
    word_order: 1,
    lang_tr: "Uzay Teleskobu",
    lang_en: "Space Telescope",
    lang_de: "Weltraumteleskop",
    lang_fr: "Télescope Spatial",
    lang_es: "Telescopio Espacial",
    lang_it: "Telescopio Spaziale",
    lang_pt: "Telescópio Espacial",
    lang_ar: "تلسكوب فضائي",
    lang_ko: "우주 망원경",
  },
];

export const MOCK_COMMUNITY_STATS: MinlanCommunityStats = {
  total_card_matches: 18420,
  target_card_matches: 25000,
};
