<**COMMENT
     Image.htm - Template for frame image
     Created by Microsoft PowerPoint 97 

     If you modify these templates, you do so at your own risk.  Make a backup copy of any
     changes you make as future installs of PowerPoint and the Internet Assistant 
     will overwrite existing templates with new versions.
**COMMENT>
<HTML>
<meta name="GENERATOR" content="Microsoft Internet Assistant for PowerPoint 97">
<BODY <**BACKCL* **BACKCL*> <**FORECL* **FORECL*> <**LINKCL* **LINKCL*> <**VISTCL* **VISTCL*> >
<base target="_top">
<CENTER>
   <**FIMAGE*  **FIMAGE*>
</CENTER>
</BODY>
</HTML>
