<**COMMENT
     Index.htm - Template for index page 
     Created by Microsoft PowerPoint 97 

     If you modify these templates, you do so at your own risk.  Make a backup copy of any
     changes you make as future installs of PowerPoint and the Internet Assistant 
     will overwrite existing templates with new versions.
**COMMENT>
<html>

<head>
<**ECODE**%s**ECODE**>
<meta name="GENERATOR" content="Microsoft Internet Assistant for PowerPoint 97">
<**PHEAD**<title>%s</title>**PHEAD**>
</head>

<BODY <**BACKCL* **BACKCL*> <**FORECL* **FORECL*> <**LINKCL* **LINKCL*> <**VISTCL* **VISTCL*> >
<CENTER>
<**PHEAD**<h1>%s</h1>**PHEAD**>
<**UDATE**<h4>%s</h4>**UDATE**>
<**START**<br><h2> %s </h2><br> **START**> 
</center>
<center>
 <table width=90%>
  <tr>
   <td valign=top align=left width=50%>
      <h3><u><**TOCTTL*%s**TOCTTL*></u></h3>
    <**TOC**** %s **TOC****>
   </td>
   <td valign=top width=50%>
	<**AUTHOR* %s **AUTHOR*>
    <**EMAIL** %s **EMAIL**>
	<**HOMEP** %s **HOMEP**>
	<**OTHER** %s **OTHER**>
	<**BESTIE* %s **BESTIE*>
	<**PPANIM* %s **PPANIM*>
	<**ORIGPR* %s **ORIGPR*>
   </td>
  </tr>
 </table>
</center>

</body>

</html>
