<**COMMENT
     Note.htm - Template for frame notes 
     Created by Microsoft PowerPoint 97 

     If you modify these templates, you do so at your own risk.  Make a backup copy of any
     changes you make as future installs of PowerPoint and the Internet Assistant 
     will overwrite existing templates with new versions.
**COMMENT>
<HTML>

<HEAD>
<**ECODE**%s**ECODE**>
<meta name="GENERATOR" content="Microsoft Internet Assistant for PowerPoint 97">
</HEAD>

<BODY <**BACKCL* **BACKCL*> <**FORECL* **FORECL*> <**LINKCL* **LINKCL*> <**VISTCL* **VISTCL*> >

<**NOTES**
  <FONT size=4><STRONG> Notes: </STRONG> </FONT>
  <HR SIZE=3>
  <P> %s </P> 
**NOTES**>

</BODY>
</HTML>
