<!Outline.TPL - Template used to generate the collapsed or expanded versions of the outline >
<! HTML for the frame based version of a presentation>
<!      Tags used:  >
<!              Head - heading of the presentation>
<!              Text - test containing the HTML code for the outline
<html>
<meta name="GENERATOR" content="Microsoft Internet Assistant for PowerPoint 97">
<! the click event needs to cause then slide image and notes to change>
<body>
<**HEAD*** <H1>%s</H1> **HEAD***>
<br>
<**TEXT*** %s **TEXT***>
</body>

</html>
