<**COMMENT
     Text.htm - template for text layout of a slide
     Created by Microsoft PowerPoint 97 

     If you modify these templates, you do so at your own risk.  Make a backup copy of any
     changes you make as future installs of PowerPoint and the Internet Assistant 
     will overwrite existing templates with new versions.
**COMMENT>
<HTML>

<HEAD>
<**ECODE**%s**ECODE**>
<meta name="GENERATOR" content="Microsoft Internet Assistant for PowerPoint 97">
<**TITLE** <TITLE>%s</TITLE> **TITLE**>
</HEAD>

<BODY <**BACKCL* **BACKCL*> <**FORECL* **FORECL*> <**LINKCL* **LINKCL*> <**VISTCL* **VISTCL*> >

<**HEAD*** <H1>%s</H1> **HEAD***>
<**TEXT*** <P>%s</P> **TEXT***>
<P>
<TABLE>
  <TD HEIGHT=100 WIDTH=100><**PREV*** %s **PREV***></TD>
  <TD HEIGHT=100 WIDTH=100><**NEXT*** %s **NEXT***></TD>
  <TD HEIGHT=100 WIDTH=150><**FIRST** %s **FIRST**></TD>
  <TD HEIGHT=100 WIDTH=150><**MODE*** %s **MODE***></TD>
</TABLE>
<BR>
</P>

<**NOTES** <FONT size=4><STRONG> Notes: </FONT></STRONG>
  <HR SIZE=3> <P> %s </P> **NOTES**>

</Body>
</HTML>
