[SETUP]

; Files in this section make up the initial list of rescue items
; Filenames starting with '@' receive special handling, user-addded
; files starting with '@' will cause an error message.
; When the '*' column is set to YES, the corresponding program will
; always be selected.  The RTL column indicates whether or not the
; program requires the Norton Libarary Overlay File (NLIBxxx.RTL)

;----------------------------------------------------------------------------------
; Item Name             360     720     1.2  1.44 2.88  HD   '*'  RTL  FileSpec
;----------------------------------------------------------------------------------

"Rescue utility",       YES,    YES,    YES, YES, YES,  YES, NO,  YES, RESCUE.EXE
"Rescue startup file (RESCUE.INI)",  YES,    YES,    YES, YES, YES,  YES, NO,  NO,  RESCUE.INI
"Norton Library Overlay File",YES, YES, YES, YES, YES,  YES, NO,  NO,  NLIB200.RTL
"autoexec.bat [autoexec.sav]",YES, YES, YES, YES, YES,  YES, NO,  NO,  @AUTOEXEC.BAT
"config.sys [config.sav]", YES, YES,    YES, YES, YES,  YES, NO,  NO,  @CONFIG.SYS
"Norton Disk Doctor",   NO,     NO,     YES, YES, YES,  NO,  NO,  YES, NDD.EXE
"NDD Message File",     NO,     NO,     YES, YES, YES,  NO,  NO,  YES, NDD.MSG
"Disk Editor",          NO,     YES,    YES, YES, YES,  NO,  NO,  YES, DISKEDIT.EXE
"Norton Safe Format",   NO,     NO,     YES, YES, YES,  NO,  NO,  YES, SFORMAT.EXE
"Unerase",              NO,     NO,     YES, YES, YES,  NO,  NO,  YES, UNERASE.EXE
"Unformat",             NO,     NO,     YES, YES, YES,  NO,  NO,  YES, UNFORMAT.EXE
"FDisk (Partitioning program)",NO, NO,  YES, YES, YES,  NO,  NO,  NO,  FDISK.EXE
"Norton Diagnostics",   NO,     NO,      NO,  NO, YES,  NO,  NO,  NO,  NDIAGS.EXE
"Diskreet startup (DISKREET.INI)",YES,    YES,    YES, YES, YES,  YES, NO,  NO, DISKREET.INI
"System file: %p               ",YES,YES,YES,YES, YES,  NO,  YES, NO,  @SYSTEM0
"System file: %p               ",YES,YES,YES,YES, YES,  NO,  YES, NO,  @SYSTEM1
"System file: %p               ",YES,YES,YES,YES, YES,  NO,  YES, NO,  @SYSTEM2
"System file: %p               ",YES,YES,YES,YES, YES,  NO,  YES, NO,  @SYSTEM3
"CMOS Data",            YES,    YES,    YES, YES, YES,  YES, YES, NO,  @CMOSINFO.DAT
"Boot Record",          YES,    YES,    YES, YES, YES,  YES, YES, NO,  @BOOTINFO.DAT
"Partition Tables",     YES,    YES,    YES, YES, YES,  YES, YES, NO,  @PARTINFO.DAT
"autoexec.bat [Rescue]",YES,    YES,    YES, YES, YES,  YES, YES, NO,  @AUTOEXEC.RSC
"config.sys [Rescue]",  YES,    YES,    YES, YES, YES,  YES, YES, NO,  @CONFIG.RSC


[INCLUDE]

; Files in this section will be included in the rescue disk ONLY if
; the file is used in autoexec.bat or config.sys.

;---------------------------------
; File Name          AUTOEXEC CONFIG
;---------------------------------

ADAPTECH.SYS,        NO,      YES
ASPI2DOS.SYS,        NO,      YES
ASPI4DOS.SYS,        NO,      YES
ASPIDISK.SYS,        NO,      YES
ASPIDOS.SYS,         NO,      YES
ASPIEDOS.SYS,        NO,      YES
ATDOSHC2.SYS,        NO,      YES
ATDOSXL.SYS,         NO,      YES
CSYQ55.SYS,          NO,      YES
DISKREET.SYS,        NO,      YES
DMDRVR.BIN,          NO,      YES
DMDRVR.SYS,          NO,      YES
DOSOAD.SYS,          NO,      YES
DUBLDISK.SYS,        NO,      YES
EDVR.SYS,            NO,      YES
ENHDISK.SYS,         NO,      YES
EVDISHK.SYS,         NO,      YES
EVDR.SYS,            NO,      YES
FDDEVICE.SYS,        NO,      YES
FIXT_DRV.SYS,        NO,      YES
FIXTDRV.SYS,         NO,      YES
GSCSI.SYS,           NO,      YES
HARDRIVE.SYS,        NO,      YES
HCD.SYS,             NO,      YES
HDRIVE.SYS,          NO,      YES
HPDISK.SYS,          NO,      YES
IBD.SYS,             NO,      YES
IDRIVE.SYS,          NO,      YES
KEYBOARD.SYS,        NO,      YES
LDRIVE.SYS,          NO,      YES
LMOUSE.COM           YES,     NO
LMOUSE.SYS           NO,      YES
MLPART.SYS,          NO,      YES
MOUSE.EXE,           YES,     NO
MOUSE.SYS,           NO,      YES
PLUSDRV.SYS,         NO,      YES
RCD.SYS,             NO,      YES
SCSI.SYS,            NO,      YES
SCSI4JR.SYS,         NO,      YES
SCSIHA.SYS,          NO,      YES
SSTBIO.SYS,          NO,      YES
SSTDRIV.SYS,         NO,      YES
SSTOR.SYS,           NO,      YES
SSTORDRV.SYS,        NO,      YES
STACKER.AT,          NO,      YES
STACKER.COM,         YES,     YES
STACKER.XT,          NO,      YES
SSWAP.COM,           YES,     YES
SYQ55.SYS,           NO,      YES
XBIOS.OVL,           NO,      YES


[AUTOEXEC]

; Minimum information to include in rescue disk's autoexec.bat file

"@ECHO OFF"
"PROMPT $p$g"

[CONFIG]

; Minimum information to include in rescue disk's Config.sys file

"BREAK = ON"
"FILES = 30"
"BUFFERS = 5"

