import { NextResponse } from "next/server";

export const revalidate = 300;

// UEFA 2024/2025 - 2026 Sezonu Resmi 36'şar Takımlı Yeni Lig Formatı (Alfabetik Sıralı - Sıfırlanmış)
const RESET_STANDINGS_ALPHABETICAL: Record<number, any[]> = {
  // 🏆 1. UEFA Şampiyonlar Ligi (36 Takım - A'dan Z'ye Sıralı, Sıfır Puan)
  2: [
    { rank: 1, team: "AC Milan", country: "İTA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 2, team: "Arsenal", country: "İNG", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 3, team: "Aston Villa", country: "İNG", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 4, team: "Atalanta", country: "İTA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 5, team: "Atletico Madrid", country: "İSP", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 6, team: "Barcelona", country: "İSP", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 7, team: "Bayer Leverkusen", country: "ALM", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 8, team: "Bayern Munich", country: "ALM", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 9, team: "Benfica", country: "POR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 10, team: "Bologna", country: "İTA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 11, team: "Borussia Dortmund", country: "ALM", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 12, team: "Brest", country: "FRA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 13, team: "Celtic", country: "İSK", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 14, team: "Club Brugge", country: "BEL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 15, team: "Crvena Zvezda", country: "SIR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 16, team: "Dinamo Zagreb", country: "HIR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 17, team: "Feyenoord", country: "HOL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 18, team: "Girona", country: "İSP", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 19, team: "Inter Milan", country: "İTA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 20, team: "Juventus", country: "İTA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 21, team: "Lille", country: "FRA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 22, team: "Liverpool", country: "İNG", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 23, team: "Manchester City", country: "İNG", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 24, team: "Monaco", country: "FRA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 25, team: "Paris Saint-Germain", country: "FRA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 26, team: "PSV Eindhoven", country: "HOL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 27, team: "RB Leipzig", country: "ALM", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 28, team: "Real Madrid", country: "İSP", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 29, team: "Red Bull Salzburg", country: "AVU", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 30, team: "Shakhtar Donetsk", country: "UKR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 31, team: "Slovan Bratislava", country: "SVK", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 32, team: "Sparta Prag", country: "ÇEK", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 33, team: "Sporting CP", country: "POR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 34, team: "Sturm Graz", country: "AVU", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 35, team: "Stuttgart", country: "ALM", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 36, team: "Young Boys", country: "İSV", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
  ],

  // 🟠 2. UEFA Avrupa Ligi (36 Takım - A'dan Z'ye Sıralı, Sıfır Puan)
  3: [
    { rank: 1, team: "Ajax", country: "HOL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 2, team: "Anderlecht", country: "BEL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 3, team: "AS Roma", country: "İTA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 4, team: "Athletic Bilbao", country: "İSP", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 5, team: "AZ Alkmaar", country: "HOL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 6, team: "Beşiktaş", country: "TÜR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 7, team: "Bodø/Glimt", country: "NOR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 8, team: "Braga", country: "POR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 9, team: "Dinamo Kiev", country: "UKR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 10, team: "Eintracht Frankfurt", country: "ALM", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 11, team: "Elfsborg", country: "İSVE", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 12, team: "FCSB", country: "ROM", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 13, team: "Fenerbahçe", country: "TÜR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 14, team: "Ferencváros", country: "MAC", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 15, team: "Galatasaray", country: "TÜR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 16, team: "Hoffenheim", country: "ALM", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 17, team: "Karabağ", country: "AZE", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 18, team: "Lazio", country: "İTA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 19, team: "Ludogorets", country: "BUL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 20, team: "Lyon", country: "FRA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 21, team: "Maccabi Tel Aviv", country: "İSR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 22, team: "Malmö FF", country: "İSVE", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 23, team: "Manchester United", country: "İNG", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 24, team: "Midtjylland", country: "DAN", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 25, team: "Nice", country: "FRA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 26, team: "Olympiakos", country: "YUN", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 27, team: "PAOK", country: "YUN", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 28, team: "Porto", country: "POR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 29, team: "Rangers", country: "İSK", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 30, team: "Real Sociedad", country: "İSP", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 31, team: "RFS", country: "LET", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 32, team: "Slavia Prag", country: "ÇEK", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 33, team: "Tottenham", country: "İNG", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 34, team: "Twente", country: "HOL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 35, team: "Union Saint-Gilloise", country: "BEL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 36, team: "Viktoria Plzen", country: "ÇEK", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
  ],

  // 🟢 3. UEFA Konferans Ligi (36 Takım - A'dan Z'ye Sıralı, Sıfır Puan)
  848: [
    { rank: 1, team: "APOEL", country: "KIB", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 2, team: "Astana", country: "KAZ", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 3, team: "Başakşehir", country: "TÜR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 4, team: "Borac Banja Luka", country: "BOS", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 5, team: "Celje", country: "SVN", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 6, team: "Cercle Brugge", country: "BEL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 7, team: "Chelsea", country: "İNG", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 8, team: "Dinamo Minsk", country: "BLR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 9, team: "Djurgarden", country: "İSVE", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 10, team: "FC Lugano", country: "İSV", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 11, team: "Fiorentina", country: "İTA", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 12, team: "Gent", country: "BEL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 13, team: "Heart of Midlothian", country: "İSK", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 14, team: "Heidenheim", country: "ALM", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 15, team: "HJK Helsinki", country: "FİN", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 16, team: "Jagiellonia", country: "POL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 17, team: "Kopenhag", country: "DAN", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 18, team: "Larne", country: "K.İR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 19, team: "LASK", country: "AVU", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 20, team: "Legia Varşova", country: "POL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 21, team: "Mlada Boleslav", country: "ÇEK", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 22, team: "Molde", country: "NOR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 23, team: "Noah", country: "ERM", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 24, team: "Olimpija Ljubljana", country: "SVN", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 25, team: "Omonia", country: "KIB", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 26, team: "Pafos", country: "KIB", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 27, team: "Panathinaikos", country: "YUN", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 28, team: "Petrocub", country: "MOL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 29, team: "Rapid Wien", country: "AVU", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 30, team: "Real Betis", country: "İSP", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 31, team: "Shamrock Rovers", country: "İRL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 32, team: "St. Gallen", country: "İSV", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 33, team: "The New Saints", country: "GAL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 34, team: "TSC Backa Topola", country: "SIR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 35, team: "Vikingur Reykjavik", country: "İZL", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
    { rank: 36, team: "Vitoria Guimaraes", country: "POR", played: 0, win: 0, draw: 0, lose: 0, gf: 0, ga: 0, gd: 0, pts: 0, form: "" },
  ]
};

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const tournamentId = parseInt(searchParams.get("tournament") || "2", 10);

  const standings = RESET_STANDINGS_ALPHABETICAL[tournamentId] || RESET_STANDINGS_ALPHABETICAL[2];

  return NextResponse.json({
    success: true,
    tournamentId,
    standings,
    isLive: false,
    message: "2024/2026 Sezonu - 36 Takım Alfabetik Sıralı (Sıfır Puan)"
  });
}
